export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

export const GET_USER_TODOS_REQUEST = 'GET_USER_TODOS_REQUEST';
export const GET_USER_TODOS_SUCCESS = 'GET_USER_TODOS_SUCCESS';
export const GET_USER_TODOS_FAIL = 'GET_USER_TODOS_FAIL';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const MARK_TODO_REQUEST = 'MARK_TODO_REQUEST';
export const MARK_TODO_SUCCESS = 'MARK_TODO_SUCCESS';
export const MARK_TODO_FAIL = 'MARK_TODO_FAIL';
