export const USER_CHECK_AUTH_REQUEST = 'USER_CHECK_AUTH_REQUEST';
export const USER_CHECK_AUTH_SUCCESS = 'USER_CHECK_AUTH_SUCCESS';
export const USER_CHECK_AUTH_FAIL = 'USER_CHECK_AUTH_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
